# Generated by Django 5.0.7 on 2024-07-30 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('star', models.IntegerField()),
                ('image', models.ImageField(upload_to='recipe-images/')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('prep', models.IntegerField()),
                ('cook', models.IntegerField()),
                ('yields', models.IntegerField()),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.recipetext')),
            ],
        ),
    ]
