# Generated by Django 5.0.7 on 2024-07-30 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='text',
        ),
        migrations.AddField(
            model_name='recipetext',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recipe.recipe'),
            preserve_default=False,
        ),
    ]
