# Generated by Django 5.0.7 on 2024-08-03 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipetext',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text', to='recipe.recipe'),
        ),
    ]
